version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.1.7

parameters:
  artifactory-url:
    description: Artifactory URL
    type: string
    default: https://rpmb.jfrog.io

workflows:
  redis6build:
    jobs:
      - docker-rpmbuild/rpmbuild:
          name: centos8redis6build
          base_service: centos8redis6base
          build_service: centos8redis6build
          bintray_uploader: centos8bintray
          bintray-repo: custom
      - docker-rpmbuild/rpmbuild:
          name: centos7redis6build
          base_service: centos7redis6base
          build_service: centos7redis6build
          bintray_uploader: centos7bintray
          bintray-repo: custom